repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v5.0.0
      hooks:
          - id: check-yaml
          - id: end-of-file-fixer
          - id: trailing-whitespace
    - repo: https://github.com/psf/black
      rev: 22.10.0
      hooks:
          - id: black
    - repo: https://github.com/astral-sh/uv-pre-commit
      # uv version.
      rev: 0.6.5
      hooks:
          - id: uv-lock
          - id: uv-export
    - repo: local
      hooks:
      -   id: update-leetcode-progress
          name: Update LeetCode progress
          entry: uv run progress_tracker.py
          language: python
          files: 'problems/.*\.py$'
          pass_filenames: false
          always_run: true
          additional_dependencies: []
      -   id: pytest-check
          name: pytest-check
          entry: pytest problems
          language: system
          pass_filenames: false
          always_run: true
